services:

  tailscale:
    image: tailscale/tailscale:latest
    environment:
      - TS_HOSTNAME=${CONF_HOSTNAME}
      - TS_AUTH_KEY=${CONF_TS_KEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:${CONF_TS_TAG}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
    volumes:
      - ../../docker-binds/mealie/tailscale/state:/var/lib/tailscale
      - ./tailscale/config:/config # for the serve.json config file
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    networks:
      - net
    healthcheck:
      test: tailscale status --peers=false --json | grep 'Online.*true'
      start_period: 3s
      interval: 1s
      retries: 3
    restart: unless-stopped

  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    volumes:
      - data:/app/data/
      - ../../docker-binds/mealie/export:/app/data/backups
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      BASE_URL: ${CONF_DOMAIN} 
      SMTP_HOST: ${CONF_SMTP_HOST}
      SMTP_FROM_EMAIL: ${CONF_SMTP_FROM_EMAIL}
      SMTP_USER: ${CONF_SMTP_USER}
      SMTP_PASSWORD: ${CONF_SMTP_PASSWORD}
      OPENAI_API_KEY: ${CONF_OPENAI_API_KEY}
    network_mode: service:tailscale
    depends_on:
      tailscale:
        condition: service_healthy
    restart: unless-stopped

volumes:
  data:

networks:
  net:
