services:
  
  tailscale:
    image: tailscale/tailscale:latest
    environment:
      - TS_HOSTNAME=${CONF_HOSTNAME}
      - TS_AUTH_KEY=${CONF_TS_KEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:${CONF_TS_TAG}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
    volumes:
      - ../../docker-binds/searxng/tailscale/state:/var/lib/tailscale
      - ./tailscale/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    networks:
      - net
    healthcheck:
      test: tailscale status --peers=false --json | grep 'Online.*true'
      start_period: 3s
      interval: 1s
      retries: 3
    restart: unless-stopped

  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ../../docker-binds/searxng/searxng:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${CONF_DOMAIN}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    network_mode: service:tailscale
    depends_on:
      tailscale:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - net
    restart: unless-stopped

volumes:
  valkey-data2:
  searxng-data:

networks:
  net:
